name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name (e.g., v1.0.0)'
        required: true

jobs:
  build:
    name: Build for ${{ matrix.os }} (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    env:
      PROJECT_NAME: Skland-Auto-Sign-In
      VERSION: ${{ github.event.inputs.tag_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            target-label: linux-x64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            target-label: windows-x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OpenSSL dev (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Install OpenSSL dev (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          choco install -y openssl

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build project (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Build project (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions-rs/cargo@v1
        env:
           OPENSSL_DIR: "C:/Program Files/OpenSSL"
           OPENSSL_LIB_DIR: "C:/Program Files/OpenSSL/lib/VC/x64/MD"
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Rename artifact
        shell: bash
        run: |
          mv target/${{ matrix.target }}/release/${{ env.PROJECT_NAME }}${{ matrix.target == 'x86_64-pc-windows-msvc' && '.exe' || '' }} ${{ env.PROJECT_NAME }}-${{ env.VERSION }}-${{ matrix.target-label }}${{ matrix.target == 'x86_64-pc-windows-msvc' && '.exe' || '' }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT_NAME }}-${{ env.VERSION }}-${{ matrix.target-label }}
          path: ${{ env.PROJECT_NAME }}-${{ env.VERSION }}-${{ matrix.target-label }}${{ matrix.target == 'x86_64-pc-windows-msvc' && '.exe' || '' }}

  create-release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: Skland-Auto-Sign-In
      VERSION: ${{ github.event.inputs.tag_name }}
    strategy:
      matrix:
        file:
          - path: 

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ env.PROJECT_NAME }} ${{ github.event.inputs.tag_name }} # Project Name + Version
          draft: false
          prerelease: false

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Upload release assets (using a script)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in ./artifacts/*; do
            filename=$(basename "$file")
            gh release upload ${{ github.event.inputs.tag_name }} "$file" --clobber
          done
